# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: slave.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='slave.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bslave.proto\"\x07\n\x05\x45mpty\"q\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x1a\n\x05stage\x18\x02 \x01(\x0e\x32\x0b.Data.Stage\"?\n\x05Stage\x12\t\n\x05TRAIN\x10\x00\x12\t\n\x05\x44\x45\x42UG\x10\x01\x12\x0b\n\x07RETRAIN\x10\x02\x12\x08\n\x04TEST\x10\x03\x12\t\n\x05QUERY\x10\x04\x32\x88\x07\n\x05Slave\x12\x1d\n\nInitialize\x12\x05.Data\x1a\x06.Empty\"\x00\x12\x1c\n\tSetSecure\x12\x05.Data\x1a\x06.Empty\"\x00\x12\x1e\n\x0bUpdateDelta\x12\x05.Data\x1a\x06.Empty\"\x00\x12\x1b\n\tGetThetaX\x12\x05.Data\x1a\x05.Data\"\x00\x12*\n\x18\x43omputeEncryptedGradient\x12\x05.Data\x1a\x05.Data\"\x00\x12 \n\rApplyGradient\x12\x05.Data\x1a\x06.Empty\"\x00\x12#\n\x10SendMasterPubKey\x12\x05.Data\x1a\x06.Empty\"\x00\x12 \n\x0eGetSlavePubKey\x12\x05.Data\x1a\x05.Data\"\x00\x12\x19\n\x06SetOpt\x12\x05.Data\x1a\x06.Empty\"\x00\x12\x1d\n\nSetWeights\x12\x05.Data\x1a\x06.Empty\"\x00\x12\x1c\n\nGetWeights\x12\x05.Data\x1a\x05.Data\"\x00\x12\"\n\x10GetThetaXForTest\x12\x05.Data\x1a\x05.Data\"\x00\x12#\n\x11GetThetaXForQuery\x12\x05.Data\x1a\x05.Data\"\x00\x12\x1f\n\rGetDebugState\x12\x05.Data\x1a\x05.Data\"\x00\x12\x1d\n\nStartDebug\x12\x05.Data\x1a\x06.Empty\"\x00\x12\x1c\n\nQGradStep1\x12\x05.Data\x1a\x05.Data\"\x00\x12\x1d\n\nQGradStep2\x12\x05.Data\x1a\x06.Empty\"\x00\x12\x1a\n\x08GetQgrad\x12\x05.Data\x1a\x05.Data\"\x00\x12\x1a\n\x08HvpStep1\x12\x05.Data\x1a\x05.Data\"\x00\x12\x1a\n\x08HvpStep2\x12\x05.Data\x1a\x05.Data\"\x00\x12\x1a\n\x08HvpStep3\x12\x05.Data\x1a\x05.Data\"\x00\x12\x19\n\x06\x43GInit\x12\x05.Data\x1a\x06.Empty\"\x00\x12\x19\n\x07\x43GGetR2\x12\x05.Data\x1a\x05.Data\"\x00\x12\x18\n\x06\x43GpHvp\x12\x05.Data\x1a\x05.Data\"\x00\x12\x1e\n\x0bUpdateZandR\x12\x05.Data\x1a\x06.Empty\"\x00\x12\x1a\n\x07UpdateP\x12\x05.Data\x1a\x06.Empty\"\x00\x12\x1c\n\nCGGetRNorm\x12\x05.Data\x1a\x05.Data\"\x00\x12\x1b\n\tInfluence\x12\x05.Data\x1a\x05.Data\"\x00\x12\x1b\n\x08\x45ndDebug\x12\x05.Data\x1a\x06.Empty\"\x00\x62\x06proto3'
)



_DATA_STAGE = _descriptor.EnumDescriptor(
  name='Stage',
  full_name='Data.Stage',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRAIN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEBUG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RETRAIN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TEST', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='QUERY', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=74,
  serialized_end=137,
)
_sym_db.RegisterEnumDescriptor(_DATA_STAGE)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=22,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Data.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stage', full_name='Data.stage', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DATA_STAGE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=137,
)

_DATA.fields_by_name['stage'].enum_type = _DATA_STAGE
_DATA_STAGE.containing_type = _DATA
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'slave_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'slave_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  })
_sym_db.RegisterMessage(Data)



_SLAVE = _descriptor.ServiceDescriptor(
  name='Slave',
  full_name='Slave',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=140,
  serialized_end=1044,
  methods=[
  _descriptor.MethodDescriptor(
    name='Initialize',
    full_name='Slave.Initialize',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetSecure',
    full_name='Slave.SetSecure',
    index=1,
    containing_service=None,
    input_type=_DATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateDelta',
    full_name='Slave.UpdateDelta',
    index=2,
    containing_service=None,
    input_type=_DATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetThetaX',
    full_name='Slave.GetThetaX',
    index=3,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ComputeEncryptedGradient',
    full_name='Slave.ComputeEncryptedGradient',
    index=4,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ApplyGradient',
    full_name='Slave.ApplyGradient',
    index=5,
    containing_service=None,
    input_type=_DATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendMasterPubKey',
    full_name='Slave.SendMasterPubKey',
    index=6,
    containing_service=None,
    input_type=_DATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSlavePubKey',
    full_name='Slave.GetSlavePubKey',
    index=7,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetOpt',
    full_name='Slave.SetOpt',
    index=8,
    containing_service=None,
    input_type=_DATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetWeights',
    full_name='Slave.SetWeights',
    index=9,
    containing_service=None,
    input_type=_DATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetWeights',
    full_name='Slave.GetWeights',
    index=10,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetThetaXForTest',
    full_name='Slave.GetThetaXForTest',
    index=11,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetThetaXForQuery',
    full_name='Slave.GetThetaXForQuery',
    index=12,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDebugState',
    full_name='Slave.GetDebugState',
    index=13,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartDebug',
    full_name='Slave.StartDebug',
    index=14,
    containing_service=None,
    input_type=_DATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QGradStep1',
    full_name='Slave.QGradStep1',
    index=15,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QGradStep2',
    full_name='Slave.QGradStep2',
    index=16,
    containing_service=None,
    input_type=_DATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetQgrad',
    full_name='Slave.GetQgrad',
    index=17,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='HvpStep1',
    full_name='Slave.HvpStep1',
    index=18,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='HvpStep2',
    full_name='Slave.HvpStep2',
    index=19,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='HvpStep3',
    full_name='Slave.HvpStep3',
    index=20,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CGInit',
    full_name='Slave.CGInit',
    index=21,
    containing_service=None,
    input_type=_DATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CGGetR2',
    full_name='Slave.CGGetR2',
    index=22,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CGpHvp',
    full_name='Slave.CGpHvp',
    index=23,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateZandR',
    full_name='Slave.UpdateZandR',
    index=24,
    containing_service=None,
    input_type=_DATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateP',
    full_name='Slave.UpdateP',
    index=25,
    containing_service=None,
    input_type=_DATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CGGetRNorm',
    full_name='Slave.CGGetRNorm',
    index=26,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Influence',
    full_name='Slave.Influence',
    index=27,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EndDebug',
    full_name='Slave.EndDebug',
    index=28,
    containing_service=None,
    input_type=_DATA,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SLAVE)

DESCRIPTOR.services_by_name['Slave'] = _SLAVE

# @@protoc_insertion_point(module_scope)
